name: discord-application-emojis-manager
packagePath: .
org: favware
monoRepo: false
tagTemplate: v{{new-version}}
identifierBase: false
pushTag: true
gitRepo: auto
gitHostVariant: github
githubRelease: true
githubReleaseLatest: true
githubReleaseNameTemplate: 'v{{new-version}}'
